#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/src/config/bootstrap.php';

$config = array_merge(require \hiqdev\composer\config\Builder::path('hidev'), [
    'basePath' => __DIR__
]);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
